xrdb -merge ~/.Xresources & # Make sure Xresources is loaded (for Urxvt config)
xhost +192.168.0.11 # Allow remote X from my device
#cairo-compmgr & # Uncomment to enable compositing (real transparency)
i3 # crazy WM of epicness
